stages:
  train:
    cmd: python src/train.py --multirun hparam=xray_vit_hparam +trainer.log_every_n_steps=5 hydra.sweeper.n_jobs=4
    deps:
    - configs/experiment/xray_ex.yaml
    - src/train.py
    outs:
    - logs:
        cache: false