name: Hyperparameter Optimization and Report

on:
  push:
    branches: [ main ]

jobs:
  optimize-and-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: iterative/setup-cml@v2
      
      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        env:
          UV_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
        run: |
          uv sync
      
      - name: Update DVC and dependencies
        run: |
          uv run pip install --upgrade dvc dvc-gdrive

      - name: Pull data from DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          uv run pip install backoff
          python - <<EOF
          import backoff
          import subprocess
          import sys

          @backoff.on_exception(backoff.expo, subprocess.CalledProcessError, max_tries=5)
          def run_dvc_pull():
              subprocess.run(["uv", "run", "dvc", "pull", "-v"], check=True)

          try:
              run_dvc_pull()
          except subprocess.CalledProcessError:
              print("DVC pull failed after multiple retries")
              sys.exit(1)
          EOF

      - name: Train model
        run: |
          uv run dvc repro

      - name: Generate results table and plots
        run: |
          uv run python scripts/generate_results.py

      - name: Run optimized training
        run: |
          uv run python scripts/train_optimized.py

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# Hyperparameter Optimization Results" >> report.md

          echo "### Combined Metrics Plot" >> report.md
          echo "![Combined Metrics Plot](./combined_metrics_plot.png)" >> report.md

          echo "### Best Hyperparameters" >> report.md
          cat optimization_results.md >> report.md

          echo "### Hyperparameters for Each Experiment" >> report.md
          cat hyperparameters_table.md >> report.md

          echo "### Test Accuracy Across Experiments (Step-wise)" >> report.md
          echo "![Test Accuracy Plot (Step-wise)](./test_accuracy_plot_step.png)" >> report.md

          echo "### Test Accuracy Across Experiments (Epoch-wise)" >> report.md
          echo "![Test Accuracy Plot (Epoch-wise)](./test_accuracy_plot_epoch.png)" >> report.md

          cml comment create --file report.md
